---
x-etcd-common: &etcd-common
  image: gcr.io/etcd-development/etcd:v3.5.4
  restart: always
  environment: &etcd-env
    ETCD_DATA_DIR: /etcd-data
    ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
    ETCD_INITIAL_CLUSTER: etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
    ETCD_INITIAL_CLUSTER_STATE: new
    ETCD_INITIAL_CLUSTER_TOKEN: etcd-token

services:
  etcd-1:
    <<: *etcd-common
    container_name: etcd-1
    ports:
      - 2379:2379
    environment:
      <<: *etcd-env
      ETCD_NAME: etcd-1
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-1:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd-1:2380
    volumes:
      - etcd-data-1:/etcd-data

  etcd-2:
    <<: *etcd-common
    container_name: etcd-2
    environment:
      <<: *etcd-env
      ETCD_NAME: etcd-2
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-2:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd-2:2380
    volumes:
      - etcd-data-2:/etcd-data

  etcd-3:
    <<: *etcd-common
    container_name: etcd-3
    environment:
      <<: *etcd-env
      ETCD_NAME: etcd-3
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-3:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd-3:2380
    volumes:
      - etcd-data-3:/etcd-data

volumes:
  etcd-data-1:
    driver: local
  etcd-data-2:
    driver: local
  etcd-data-3:
    driver: local
